---
version: "2"
services:
  homer:
    image: b4bz/homer
    #To build from source, comment previous line and uncomment below
    #build: .
    container_name: homer
    volumes:
      - /your/local/assets/:/www/assets
    ports:
      - 8089:8089
    user: 1000:1000 # default
    environment:
      - INIT_ASSETS=1 # default
